
package com.service.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "simple", targetNamespace = "http://www.service.com/example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Simple {


    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.service.com/example/NewOperation")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.service.com/example/", className = "com.service.example.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.service.com/example/", className = "com.service.example.NewOperationResponse")
    public String newOperation(
        @WebParam(name = "in", targetNamespace = "")
        String in);

}
