
package com.easyjet.schema.easyjetsvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EasyJetsvc", targetNamespace = "http://www.easyjet.com/schema/easyjetsvc", wsdlLocation = "file:/C:/%20sreenuTech/EasyjetairlineSVC_Schema/src/main/resources/EAService.wsdl")
public class EasyJetsvc
    extends javax.xml.ws.Service
{

    private final static URL EASYJETSVC_WSDL_LOCATION;
    private final static WebServiceException EASYJETSVC_EXCEPTION;
    private final static QName EASYJETSVC_QNAME = new QName("http://www.easyjet.com/schema/easyjetsvc", "EasyJetsvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/%20sreenuTech/EasyjetairlineSVC_Schema/src/main/resources/EAService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EASYJETSVC_WSDL_LOCATION = url;
        EASYJETSVC_EXCEPTION = e;
    }

    public EasyJetsvc() {
        super(__getWsdlLocation(), EASYJETSVC_QNAME);
    }

    public EasyJetsvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), EASYJETSVC_QNAME, features);
    }

    public EasyJetsvc(URL wsdlLocation) {
        super(wsdlLocation, EASYJETSVC_QNAME);
    }

    public EasyJetsvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EASYJETSVC_QNAME, features);
    }

    public EasyJetsvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EasyJetsvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "EaservicePort")
    public com.easyjet.schema.easyjetsvc.Service getEaservicePort() {
        return super.getPort(new QName("http://www.easyjet.com/schema/easyjetsvc", "EaservicePort"), Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "EaservicePort")
    public com.easyjet.schema.easyjetsvc.Service getEaservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.easyjet.com/schema/easyjetsvc", "EaservicePort"), Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EASYJETSVC_EXCEPTION!= null) {
            throw EASYJETSVC_EXCEPTION;
        }
        return EASYJETSVC_WSDL_LOCATION;
    }

}
