
package org.example._final;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "final", targetNamespace = "http://www.example.org/final/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Final {


    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/final/NewOperation")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/final/", className = "org.example._final.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/final/", className = "org.example._final.NewOperationResponse")
    public String newOperation(
        @WebParam(name = "in", targetNamespace = "")
        String in);

}
