
package org.example._final;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "final", targetNamespace = "http://www.example.org/final/", wsdlLocation = "file:/C:/sreenuTech/example/WebContent/WEB-INF/final.wsdl")
public class Final_Service
    extends Service
{

    private final static URL FINAL_WSDL_LOCATION;
    private final static WebServiceException FINAL_EXCEPTION;
    private final static QName FINAL_QNAME = new QName("http://www.example.org/final/", "final");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/sreenuTech/example/WebContent/WEB-INF/final.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINAL_WSDL_LOCATION = url;
        FINAL_EXCEPTION = e;
    }

    public Final_Service() {
        super(__getWsdlLocation(), FINAL_QNAME);
    }

    public Final_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINAL_QNAME, features);
    }

    public Final_Service(URL wsdlLocation) {
        super(wsdlLocation, FINAL_QNAME);
    }

    public Final_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINAL_QNAME, features);
    }

    public Final_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Final_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Final
     */
    @WebEndpoint(name = "finalSOAP")
    public Final getFinalSOAP() {
        return super.getPort(new QName("http://www.example.org/final/", "finalSOAP"), Final.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Final
     */
    @WebEndpoint(name = "finalSOAP")
    public Final getFinalSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/final/", "finalSOAP"), Final.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINAL_EXCEPTION!= null) {
            throw FINAL_EXCEPTION;
        }
        return FINAL_WSDL_LOCATION;
    }

}
