
package com.ij;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Employee", targetNamespace = "http://ij.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Employee {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ij.Employeedemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmp", targetNamespace = "http://ij.com/", className = "com.ij.GetEmp")
    @ResponseWrapper(localName = "getEmpResponse", targetNamespace = "http://ij.com/", className = "com.ij.GetEmpResponse")
    @Action(input = "http://ij.com/Employee/getEmpRequest", output = "http://ij.com/Employee/getEmpResponse")
    public Employeedemo getEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        Employeedemo arg0);

}
