
package org.example.irfan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "airjet", targetNamespace = "http://www.example.org/irfan/", wsdlLocation = "file:/C:/%20sreenuTech/easyjet/src/xsd/irfan.wsdl")
public class Airjet
    extends Service
{

    private final static URL AIRJET_WSDL_LOCATION;
    private final static WebServiceException AIRJET_EXCEPTION;
    private final static QName AIRJET_QNAME = new QName("http://www.example.org/irfan/", "airjet");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/%20sreenuTech/easyjet/src/xsd/irfan.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIRJET_WSDL_LOCATION = url;
        AIRJET_EXCEPTION = e;
    }

    public Airjet() {
        super(__getWsdlLocation(), AIRJET_QNAME);
    }

    public Airjet(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIRJET_QNAME, features);
    }

    public Airjet(URL wsdlLocation) {
        super(wsdlLocation, AIRJET_QNAME);
    }

    public Airjet(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIRJET_QNAME, features);
    }

    public Airjet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Airjet(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Irfan
     */
    @WebEndpoint(name = "irfanSOAP")
    public Irfan getIrfanSOAP() {
        return super.getPort(new QName("http://www.example.org/irfan/", "irfanSOAP"), Irfan.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Irfan
     */
    @WebEndpoint(name = "irfanSOAP")
    public Irfan getIrfanSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/irfan/", "irfanSOAP"), Irfan.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIRJET_EXCEPTION!= null) {
            throw AIRJET_EXCEPTION;
        }
        return AIRJET_WSDL_LOCATION;
    }

}
