
package com.easyjet.airlines.easervice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EAService", targetNamespace = "http://www.easyjet.com/airlines//easervice", wsdlLocation = "file:/C:/%20sreenuTech/demowsdl/src/xsd/NewWSDLFile.wsdl")
public class EAService_Service
    extends Service
{

    private final static URL EASERVICE_WSDL_LOCATION;
    private final static WebServiceException EASERVICE_EXCEPTION;
    private final static QName EASERVICE_QNAME = new QName("http://www.easyjet.com/airlines//easervice", "EAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/%20sreenuTech/demowsdl/src/xsd/NewWSDLFile.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EASERVICE_WSDL_LOCATION = url;
        EASERVICE_EXCEPTION = e;
    }

    public EAService_Service() {
        super(__getWsdlLocation(), EASERVICE_QNAME);
    }

    public EAService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EASERVICE_QNAME, features);
    }

    public EAService_Service(URL wsdlLocation) {
        super(wsdlLocation, EASERVICE_QNAME);
    }

    public EAService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EASERVICE_QNAME, features);
    }

    public EAService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EAService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EAService
     */
    @WebEndpoint(name = "EAServiceSOAP")
    public EAService getEAServiceSOAP() {
        return super.getPort(new QName("http://www.easyjet.com/airlines//easervice", "EAServiceSOAP"), EAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EAService
     */
    @WebEndpoint(name = "EAServiceSOAP")
    public EAService getEAServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.easyjet.com/airlines//easervice", "EAServiceSOAP"), EAService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EASERVICE_EXCEPTION!= null) {
            throw EASERVICE_EXCEPTION;
        }
        return EASERVICE_WSDL_LOCATION;
    }

}
