
package com.service.film;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "simpleservice", targetNamespace = "http://www.service.com/film/", wsdlLocation = "file:/C:/sreenuTech/simple11/src/com/ij/film.wsdl")
public class Simpleservice
    extends Service
{

    private final static URL SIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESERVICE_EXCEPTION;
    private final static QName SIMPLESERVICE_QNAME = new QName("http://www.service.com/film/", "simpleservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/sreenuTech/simple11/src/com/ij/film.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESERVICE_WSDL_LOCATION = url;
        SIMPLESERVICE_EXCEPTION = e;
    }

    public Simpleservice() {
        super(__getWsdlLocation(), SIMPLESERVICE_QNAME);
    }

    public Simpleservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESERVICE_QNAME, features);
    }

    public Simpleservice(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESERVICE_QNAME);
    }

    public Simpleservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESERVICE_QNAME, features);
    }

    public Simpleservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Simpleservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Film
     */
    @WebEndpoint(name = "filmSOAP")
    public Film getFilmSOAP() {
        return super.getPort(new QName("http://www.service.com/film/", "filmSOAP"), Film.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Film
     */
    @WebEndpoint(name = "filmSOAP")
    public Film getFilmSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.service.com/film/", "filmSOAP"), Film.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESERVICE_EXCEPTION!= null) {
            throw SIMPLESERVICE_EXCEPTION;
        }
        return SIMPLESERVICE_WSDL_LOCATION;
    }

}
